### ISSUE TITLE
missing .pir files during ComputeConsensus

### ISSUE THREAD

**Issue by bumproo** [ucagenomix/sicelore#13]
Hi,

I'm seeing a errors about not being able to find .pir files during the quickrun.sh test.
the tmp directory contains 535 fa files.
I think the problem might be due to picard but I am having trouble getting around it.
"Provider GCS is not available; Picard version: null"
I have picard installed:
/home/software/picard/picard-2.18.26/picard.jar
but am not sure how to call it correctly inside ComputeConsensus
Do you have any tips?
Thanks!

The top of the error stream is pasted below.

[Sun Jul 05 05:44:59 EDT 2020] ComputeConsensus INPUT=/home/charliew/ostrom/projects/lilunho-Kellis/061720_seqComparisons/data/sicelore/output_dir/GEUS10xAttributes_umifound_.bam OUTPUT=/home/charliew/ostrom/projects/lilunho-Kellis/061720_seqComparisons/data/sicelore/output_dir/consensus.fa NTHREADS=10 TMPDIR=/home/charliew/ostrom/projects/lilunho-Kellis/061720_seqComparisons/data/sicelore/output_dir/tmp/    CELLTAG=BC UMITAG=U8 GENETAG=IG TSOENDTAG=TE UMIENDTAG=UE POLYAENDTAG=PE USTAG=US RNTAG=RN MAXCLIP=150 MAPQV0=false MAXREADS=20 VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Sun Jul 05 05:44:59 EDT 2020] Executing as charliew@c19.private on Linux 3.10.0-514.2.2.el7.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_121-b13; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: null
INFO    2020-07-05 05:44:59     LongreadParser          start...
INFO    2020-07-05 05:45:00     LongreadParser          end...
INFO    2020-07-05 05:45:00     LongreadParser          Total SAMrecords        [3920]
INFO    2020-07-05 05:45:00     LongreadParser          SAMrecords valid        [3778]
INFO    2020-07-05 05:45:00     LongreadParser          SAMrecords unvalid      [142]
INFO    2020-07-05 05:45:00     LongreadParser          SAMrecords mapqv=0      [0]
INFO    2020-07-05 05:45:00     LongreadParser          SAMrecords no gene      [0]
INFO    2020-07-05 05:45:00     LongreadParser          SAMrecords no UMI       [0]
INFO    2020-07-05 05:45:00     LongreadParser          SAMrecords chimeria     [142]
INFO    2020-07-05 05:45:00     LongreadParser          SAMrecords reversed     [0]
INFO    2020-07-05 05:45:00     LongreadParser          Total reads             [3778]
INFO    2020-07-05 05:45:00     LongreadParser          Total reads multiSAM    [0]
INFO    2020-07-05 05:45:00     MoleculeDataset         MoleculeDataset init start...
INFO    2020-07-05 05:45:00     MoleculeDataset         Total molecules         610
INFO    2020-07-05 05:45:00     MoleculeDataset         Total molecule reads            3778
INFO    2020-07-05 05:45:00     MoleculeDataset         Total molecule multiIG  0
INFO    2020-07-05 05:45:00     MoleculeDataset         Calling consensus start with 10 threads
INFO    2020-07-05 05:45:00     MoleculeDataset         Total consensus to compute      610
java.io.FileNotFoundException: /home/charliew/ostrom/projects/lilunho-Kellis/061720_seqComparisons/data/sicelore/output_dir/tmp/CCGTACTTCACTATTC-AACGTTGGTT-5.pir (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at java.io.FileReader.<init>(FileReader.java:58)
        at org.ipmc.sicelore.utils.Consensus.call(Consensus.java:145)
        at org.ipmc.sicelore.utils.Consensus.call(Consensus.java:16)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
java.io.FileNotFoundException: /home/charliew/ostrom/projects/lilunho-Kellis/061720_seqComparisons/data/sicelore/output_dir/tmp/GATCGATCAACTGCTA-AAGGAGGCGT-5.pir (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at java.io.FileReader.<init>(FileReader.java:58)
        at org.ipmc.sicelore.utils.Consensus.call(Consensus.java:145)
        at org.ipmc.sicelore.utils.Consensus.call(Consensus.java:16)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
java.io.FileNotFoundException: /home/charliew/ostrom/projects/lilunho-Kellis/061720_seqComparisons/data/sicelore/output_dir/tmp/AAACGGGTCTCGGACG-CGGCCCCGCC-3.pir (No such file or directory)

**Comment by bumproo** [comment]
Please disregard this, it is a duplicate question
