### ISSUE TITLE
whether  longer  barcode  can be used for umiBCLength

### ISSUE THREAD

**Issue by liruixue0728** [ucagenomix/sicelore#29]
Now , i'm using Illumina Data from another platform to assign barcode(BC) and UMI for ONT sequences. And the length of BC is 57 nt, so I change the umiBCLength in Jar/bcMaxEditDistances.xml  to 57.  When I run the NanoporeBC_UMI_finder-1.0.jar, I got a error: 

2021-03-24 11:49:19 DEBUG NanoPoreSeqAnalyzer_new:201 - Read : 3a81e4b1-16cc-4e77-8d85-884427e5d9f0_FWD_pA_Ad3p failed
java.lang.ArrayIndexOutOfBoundsException: 56
	at com.rw.nuc.encoding.TwoBit.NucleicAcidTwoBitPerBase.get0bitsForPosition(NucleicAcidTwoBitPerBase.java:117) ~[TwoFourBitNucAcidLibraryMaven-1.0.jar:?]
	at com.rw.nuc.encoding.TwoBit.NucleicAcidTwoBitPerBase.getLongHashReplaceByteDeg(NucleicAcidTwoBitPerBase.java:199) ~[TwoFourBitNucAcidLibraryMaven-1.0.jar:?]
	at com.rw.nuc.encoding.TwoBit.ed.NucTwoBitPerBaseEDtester.substitutions(NucTwoBitPerBaseEDtester.java:163) ~[NanoporeBC_UMI_finder-1.0.jar:?]
	at com.rw.nuc.encoding.TwoBit.ed.NucTwoBitPerBaseEDtester.matchesSeqEditDistance(NucTwoBitPerBaseEDtester.java:139) ~[NanoporeBC_UMI_finder-1.0.jar:?]
	at com.rw.illuminaoxfordmerger.analyzers.BarcodeAnalyzer.lambda$testBarcodes$1(BarcodeAnalyzer.java:253) ~[NanoporeBC_UMI_finder-1.0.jar:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1352) ~[?:?]
	at java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:390) ~[?:?]
	at java.util.stream.Sink$ChainedReference.end(Sink.java:258) ~[?:?]
	at java.util.stream.Sink$ChainedInt.end(Sink.java:290) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:430) ~[?:?]
	at com.rw.illuminaoxfordmerger.analyzers.BarcodeAnalyzer.testBarcodes(BarcodeAnalyzer.java:232) ~[NanoporeBC_UMI_finder-1.0.jar:?]
	at com.rw.illuminaoxfordmerger.analyzers.BarcodeAnalyzer.findCellBC(BarcodeAnalyzer.java:88) ~[NanoporeBC_UMI_finder-1.0.jar:?]
	at com.rw.illuminaoxfordmerger.OneNanoporeSeqAnalyzer.analyze(OneNanoporeSeqAnalyzer.java:108) ~[NanoporeBC_UMI_finder-1.0.jar:?]
	at com.rw.illuminaoxfordmerger.NanoPoreSeqAnalyzer_new$NanoporeSeqListWorker.call(NanoPoreSeqAnalyzer_new.java:195) [NanoporeBC_UMI_finder-1.0.jar:?]
	at com.rw.illuminaoxfordmerger.NanoPoreSeqAnalyzer_new$NanoporeSeqListWorker.call(NanoPoreSeqAnalyzer_new.java:172) [NanoporeBC_UMI_finder-1.0.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1158) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:632) [?:?]
	at java.lang.Thread.run(Thread.java:804) [?:?]
.......

**Comment by RainerWaldmann** [comment]
It won't work for > 32 nt barcodes. This is why you are getting an exception. 
Why do you want to use 57 nt barcodes. Nanopore sequencing accuracy got meanwhile pretty good now and 16 nt. barcodes are long enough. 

Rainer
