### ISSUE TITLE
java.lang.OutOfMemoryError when running NanoporeBC_UMI_finder-1.0.jar

### ISSUE THREAD

**Issue by yangao07** [ucagenomix/sicelore#30]
Hi,
I am trying sicelore on our single-cell long-read data, the first several steps went smoothly,
however, I keep getting this "java.lang.OutOfMemoryError" when running NanoporeBC_UMI_finder.

Here is the command I used and the error message:

```
/cm/shared/apps_chop/jdk/1.8.0_144/bin/java -jar -Xmx4g /home/gaoy1/software/sicelore//Jar/NanoporeBC_UMI_finder-1.0.jar -i /home/gaoy1/sdata/sclong/PC3E_GS689/sicelore_out/GEUS.chr1.bam -o /home/gaoy1/sdata/sclong/PC3E_GS689/sicelore_out/GEUS10xAttributes.chr1.bam -k /home/gaoy1/sdata/sclong/PC3E_GS689/sicelore_out/PG.illumina.chr1.bam.obj --maxUMIfalseMatchPercent 1 --maxBCfalseMatchPercent 5 --logFile /home/gaoy1/sdata/sclong/PC3E_GS689/sicelore_out/out.log --ncpu 1
+++++++   NanoporeBC_UMI_finder 1.002  Build Dec 27, 2019++++++++++++
READING config FILE: config.xml
Trying current working directory: /scr1/users/gaoy1/sclong/PC3E_GS689/sicelore_out/passed/config.xml
Not found trying application root:/home/gaoy1/software/sicelore/Jar/config.xml
O.K. Found and using /home/gaoy1/software/sicelore/Jar/config.xml
Reading Illumina Data: /home/gaoy1/sdata/sclong/PC3E_GS689/sicelore_out/PG.illumina.chr1.bam.obj
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.io.ObjectInputStream$HandleTable.grow(ObjectInputStream.java:3793)
        at java.io.ObjectInputStream$HandleTable.assign(ObjectInputStream.java:3599)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2018)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
        at java.util.HashSet.readObject(HashSet.java:333)
        at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1058)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2136)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2027)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
        at java.util.HashMap.readObject(HashMap.java:1404)
        at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1058)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2136)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2027)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
        at java.util.HashMap.readObject(HashMap.java:1404)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1058)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2136)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2027)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535)

```

I used `/usr/bin/time` to count the memory used:
```
425.79user 16.31system 0:46.93elapsed 941%CPU (0avgtext+0avgdata 4522360maxresident)k
1597824inputs+424outputs (65major+6958632minor)pagefaults 0swaps
```
Seems like only about 4GB was used, which is far less than the total memory I allocated.

Any suggestion would be very helpful, looking forward to your reply. 
Thanks!

Yan Gao

**Comment by ucagenomix** [comment]
hi,
you are specifying a max amount of 4g for memory heap space using "-Xmx4g" parameter
increase it using -Xmx40g for instance.
best,

**Comment by yangao07** [comment]
Aha, a stupid mistake.
Thanks for the quick response!
Yan

**Comment by yangao07** [comment]
Hi,
I will just use this old issue. I was runing sicelore on the 951 cells dataset. 
The other steps went well, but the consensus calling step always got killed.
I set `-Xmx` as `256g`, is this still not enough for this dataset?

Here is my command and the error msg:
`/cm/local/apps/slurm/var/spool/job1909479/slurm_script: line 2: 1481652 Killed                  /usr/bin/java -jar -Xmx256g /home/gaoy1/software/sicelore//Jar/Sicelore-1.0.jar ComputeConsensus T=4 I=/home/gaoy1/sdata/umi_nc/951c//GEUS10xAttributes_umifound_.bam O=/home/gaoy1/sdata/umi_nc/951c//consensus.fa TMPDIR=/home/gaoy1/sdata/umi_nc/951c/tmp/ MAX_RECORDS_IN_RAM=50000`

Any comments are appreciated!
Thanks!
Yan

**Comment by ucagenomix** [comment]
Hi Yan,

ComputeConsensus pipeline does not need so much RAM, 
It must be something else. Could you copy/paste the logs ?
Do the quickrun.sh and quickrun_v2.sh scripts are running well on your environment ?

kevin

**Comment by yangao07** [comment]
I have successfully run it on the 190 cells dataset. So I assume the quickrun.sh could also work well.

Here is the log file for the 951 cells:
```
[Tue May 04 06:36:33 EDT 2021] ComputeConsensus INPUT=/home/gaoy1/sdata/umi_nc/951c/GEUS10xAttributes_umifound_.bam OUTPUT=/home/gaoy1/sdata/umi_nc/951c/consensus.fa NTHREADS=4 TMPDIR=/home/gaoy1/sdata/umi_nc/951c/tmp/ MAX_RECORDS_IN_RAM=50000    CELLTAG=BC UMITAG=U8 GENETAG=IG TSOENDTAG=TE UMIENDTAG=UE POLYAENDTAG=PE USTAG=US RNTAG=RN MAXCLIP=150 MAPQV0=false MAXREADS=20 VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Tue May 04 06:36:33 EDT 2021] Executing as gaoy1@m-4-03 on Linux 4.18.0-193.28.1.el8_2.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_272-b10; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: null
INFO	2021-05-04 06:36:33	LongreadParser		start...
INFO	2021-05-04 06:38:03	LongreadParser		Processed	     1,000,000 Records.  Elapsed time: 00:01:29s.  Time for last 1,000,000:   89s.  Last read position: 1:53,313,651
INFO	2021-05-04 06:40:01	LongreadParser		Processed	     2,000,000 Records.  Elapsed time: 00:03:28s.  Time for last 1,000,000:  118s.  Last read position: 1:95,498,593
INFO	2021-05-04 06:42:30	LongreadParser		Processed	     3,000,000 Records.  Elapsed time: 00:05:56s.  Time for last 1,000,000:  148s.  Last read position: 1:180,568,944
INFO	2021-05-04 06:45:18	LongreadParser		Processed	     4,000,000 Records.  Elapsed time: 00:08:44s.  Time for last 1,000,000:  167s.  Last read position: 10:61,738,665
INFO	2021-05-04 06:47:58	LongreadParser		Processed	     5,000,000 Records.  Elapsed time: 00:11:24s.  Time for last 1,000,000:  160s.  Last read position: 10:110,920,180
INFO	2021-05-04 06:50:33	LongreadParser		Processed	     6,000,000 Records.  Elapsed time: 00:13:59s.  Time for last 1,000,000:  155s.  Last read position: 11:29,545,848
INFO	2021-05-04 06:52:27	LongreadParser		Processed	     7,000,000 Records.  Elapsed time: 00:15:53s.  Time for last 1,000,000:  114s.  Last read position: 11:59,183,875
INFO	2021-05-04 06:54:42	LongreadParser		Processed	     8,000,000 Records.  Elapsed time: 00:18:08s.  Time for last 1,000,000:  134s.  Last read position: 11:78,323,159
INFO	2021-05-04 06:57:19	LongreadParser		Processed	     9,000,000 Records.  Elapsed time: 00:20:45s.  Time for last 1,000,000:  157s.  Last read position: 11:104,408,016
INFO	2021-05-04 07:00:19	LongreadParser		Processed	    10,000,000 Records.  Elapsed time: 00:23:45s.  Time for last 1,000,000:  180s.  Last read position: 12:5,342,113
INFO	2021-05-04 07:02:29	LongreadParser		Processed	    11,000,000 Records.  Elapsed time: 00:25:55s.  Time for last 1,000,000:  129s.  Last read position: 12:71,016,036
INFO	2021-05-04 07:04:43	LongreadParser		Processed	    12,000,000 Records.  Elapsed time: 00:28:09s.  Time for last 1,000,000:  134s.  Last read position: 12:110,692,697
INFO	2021-05-04 07:06:55	LongreadParser		Processed	    13,000,000 Records.  Elapsed time: 00:30:21s.  Time for last 1,000,000:  131s.  Last read position: 13:34,127,224
INFO	2021-05-04 07:09:57	LongreadParser		Processed	    14,000,000 Records.  Elapsed time: 00:33:23s.  Time for last 1,000,000:  182s.  Last read position: 13:90,923,183
INFO	2021-05-04 07:11:57	LongreadParser		Processed	    15,000,000 Records.  Elapsed time: 00:35:23s.  Time for last 1,000,000:  120s.  Last read position: 14:29,968,431
INFO	2021-05-04 07:14:02	LongreadParser		Processed	    16,000,000 Records.  Elapsed time: 00:37:29s.  Time for last 1,000,000:  125s.  Last read position: 14:75,845,333
INFO	2021-05-04 07:16:37	LongreadParser		Processed	    17,000,000 Records.  Elapsed time: 00:40:03s.  Time for last 1,000,000:  154s.  Last read position: 15:58,933,804
INFO	2021-05-04 07:19:14	LongreadParser		Processed	    18,000,000 Records.  Elapsed time: 00:42:40s.  Time for last 1,000,000:  157s.  Last read position: 15:98,949,836
INFO	2021-05-04 07:21:32	LongreadParser		Processed	    19,000,000 Records.  Elapsed time: 00:44:58s.  Time for last 1,000,000:  137s.  Last read position: 16:16,819,699
INFO	2021-05-04 07:24:33	LongreadParser		Processed	    20,000,000 Records.  Elapsed time: 00:47:59s.  Time for last 1,000,000:  181s.  Last read position: 16:76,403,190
INFO	2021-05-04 07:26:45	LongreadParser		Processed	    21,000,000 Records.  Elapsed time: 00:50:11s.  Time for last 1,000,000:  132s.  Last read position: 17:25,262,233
INFO	2021-05-04 07:29:40	LongreadParser		Processed	    22,000,000 Records.  Elapsed time: 00:53:06s.  Time for last 1,000,000:  174s.  Last read position: 17:42,469,090
INFO	2021-05-04 07:32:13	LongreadParser		Processed	    23,000,000 Records.  Elapsed time: 00:55:39s.  Time for last 1,000,000:  152s.  Last read position: 18:25,138,618
INFO	2021-05-04 07:34:38	LongreadParser		Processed	    24,000,000 Records.  Elapsed time: 00:58:04s.  Time for last 1,000,000:  144s.  Last read position: 19:3,908,871
INFO	2021-05-04 07:36:39	LongreadParser		Processed	    25,000,000 Records.  Elapsed time: 01:00:05s.  Time for last 1,000,000:  121s.  Last read position: 19:21,272,288
INFO	2021-05-04 07:40:34	LongreadParser		Processed	    26,000,000 Records.  Elapsed time: 01:04:00s.  Time for last 1,000,000:  234s.  Last read position: 2:24,985,950
INFO	2021-05-04 07:43:00	LongreadParser		Processed	    27,000,000 Records.  Elapsed time: 01:06:27s.  Time for last 1,000,000:  146s.  Last read position: 2:63,023,763
INFO	2021-05-04 07:47:00	LongreadParser		Processed	    28,000,000 Records.  Elapsed time: 01:10:26s.  Time for last 1,000,000:  239s.  Last read position: 2:122,096,067
INFO	2021-05-04 07:49:12	LongreadParser		Processed	    29,000,000 Records.  Elapsed time: 01:12:38s.  Time for last 1,000,000:  131s.  Last read position: 2:164,879,384
INFO	2021-05-04 07:51:00	LongreadParser		Processed	    30,000,000 Records.  Elapsed time: 01:14:26s.  Time for last 1,000,000:  107s.  Last read position: 3:53,856,591
INFO	2021-05-04 07:53:18	LongreadParser		Processed	    31,000,000 Records.  Elapsed time: 01:16:44s.  Time for last 1,000,000:  137s.  Last read position: 3:96,727,556
INFO	2021-05-04 07:55:26	LongreadParser		Processed	    32,000,000 Records.  Elapsed time: 01:18:52s.  Time for last 1,000,000:  128s.  Last read position: 4:3,834,475
INFO	2021-05-04 07:57:30	LongreadParser		Processed	    33,000,000 Records.  Elapsed time: 01:20:56s.  Time for last 1,000,000:  123s.  Last read position: 4:69,925,175
INFO	2021-05-04 07:59:54	LongreadParser		Processed	    34,000,000 Records.  Elapsed time: 01:23:20s.  Time for last 1,000,000:  144s.  Last read position: 4:119,195,390
INFO	2021-05-04 08:03:10	LongreadParser		Processed	    35,000,000 Records.  Elapsed time: 01:26:36s.  Time for last 1,000,000:  195s.  Last read position: 4:137,319,700
INFO	2021-05-04 08:07:46	LongreadParser		Processed	    36,000,000 Records.  Elapsed time: 01:31:12s.  Time for last 1,000,000:  276s.  Last read position: 5:31,453,272
INFO	2021-05-04 08:10:19	LongreadParser		Processed	    37,000,000 Records.  Elapsed time: 01:33:45s.  Time for last 1,000,000:  153s.  Last read position: 5:110,911,348
INFO	2021-05-04 08:12:45	LongreadParser		Processed	    38,000,000 Records.  Elapsed time: 01:36:11s.  Time for last 1,000,000:  145s.  Last read position: 5:132,115,327
INFO	2021-05-04 08:14:48	LongreadParser		Processed	    39,000,000 Records.  Elapsed time: 01:38:14s.  Time for last 1,000,000:  123s.  Last read position: 6:30,805,746
INFO	2021-05-04 08:17:00	LongreadParser		Processed	    40,000,000 Records.  Elapsed time: 01:40:26s.  Time for last 1,000,000:  132s.  Last read position: 6:86,395,633
INFO	2021-05-04 08:19:20	LongreadParser		Processed	    41,000,000 Records.  Elapsed time: 01:42:47s.  Time for last 1,000,000:  140s.  Last read position: 6:140,554,710
INFO	2021-05-04 08:21:08	LongreadParser		Processed	    42,000,000 Records.  Elapsed time: 01:44:35s.  Time for last 1,000,000:  108s.  Last read position: 7:28,194,518
INFO	2021-05-04 08:26:54	LongreadParser		Processed	    43,000,000 Records.  Elapsed time: 01:50:20s.  Time for last 1,000,000:  345s.  Last read position: 7:59,278,565
INFO	2021-05-04 08:29:23	LongreadParser		Processed	    44,000,000 Records.  Elapsed time: 01:52:50s.  Time for last 1,000,000:  149s.  Last read position: 7:109,519,584
INFO	2021-05-04 08:35:44	LongreadParser		Processed	    45,000,000 Records.  Elapsed time: 01:59:10s.  Time for last 1,000,000:  380s.  Last read position: 8:13,884,797
INFO	2021-05-04 08:38:08	LongreadParser		Processed	    46,000,000 Records.  Elapsed time: 02:01:35s.  Time for last 1,000,000:  144s.  Last read position: 8:71,542,817
INFO	2021-05-04 08:40:30	LongreadParser		Processed	    47,000,000 Records.  Elapsed time: 02:03:56s.  Time for last 1,000,000:  141s.  Last read position: 8:119,809,217
INFO	2021-05-04 08:42:45	LongreadParser		Processed	    48,000,000 Records.  Elapsed time: 02:06:11s.  Time for last 1,000,000:  134s.  Last read position: 9:36,832,801
INFO	2021-05-04 08:45:08	LongreadParser		Processed	    49,000,000 Records.  Elapsed time: 02:08:35s.  Time for last 1,000,000:  143s.  Last read position: 9:64,340,366
INFO	2021-05-04 08:47:28	LongreadParser		Processed	    50,000,000 Records.  Elapsed time: 02:10:54s.  Time for last 1,000,000:  139s.  Last read position: 9:106,453,956
INFO	2021-05-04 08:49:26	LongreadParser		Processed	    51,000,000 Records.  Elapsed time: 02:12:52s.  Time for last 1,000,000:  117s.  Last read position: MT:7,772
INFO	2021-05-04 08:51:37	LongreadParser		Processed	    52,000,000 Records.  Elapsed time: 02:15:04s.  Time for last 1,000,000:  131s.  Last read position: X:75,514,334
INFO	2021-05-04 08:53:35	LongreadParser		Processed	    53,000,000 Records.  Elapsed time: 02:17:02s.  Time for last 1,000,000:  117s.  Last read position: X:166,499,869
INFO	2021-05-04 08:54:37	LongreadParser		end...
INFO	2021-05-04 08:54:37	LongreadParser		Total SAMrecords	[53364057]
INFO	2021-05-04 08:54:37	LongreadParser		SAMrecords valid	[41421124]
INFO	2021-05-04 08:54:37	LongreadParser		SAMrecords unvalid	[11942933]
INFO	2021-05-04 08:54:37	LongreadParser		SAMrecords mapqv=0	[9265910]
INFO	2021-05-04 08:54:37	LongreadParser		SAMrecords no gene	[0]
INFO	2021-05-04 08:54:37	LongreadParser		SAMrecords no UMI	[0]
INFO	2021-05-04 08:54:37	LongreadParser		SAMrecords chimeria	[2677023]
INFO	2021-05-04 08:54:37	LongreadParser		SAMrecords reversed	[0]
INFO	2021-05-04 08:54:37	LongreadParser		Total reads		[41421124]
INFO	2021-05-04 08:54:37	LongreadParser		Total reads multiSAM	[0]
INFO	2021-05-04 08:54:37	MoleculeDataset		MoleculeDataset init start...
INFO	2021-05-04 09:01:31	MoleculeDataset		Total molecules		8274512
INFO	2021-05-04 09:01:37	MoleculeDataset		Total molecule reads		41421124
INFO	2021-05-04 09:01:37	MoleculeDataset		Total molecule multiIG	54174
INFO	2021-05-04 09:01:37	MoleculeDataset		Calling consensus start with 4 threads
/cm/local/apps/slurm/var/spool/job1909479/slurm_script: line 2: 1481652 Killed                  /usr/bin/java -jar -Xmx256g /home/gaoy1/software/sicelore//Jar/Sicelore-1.0.jar ComputeConsensus T=4 I=/home/gaoy1/sdata/umi_nc/951c//GEUS10xAttributes_umifound_.bam O=/home/gaoy1/sdata/umi_nc/951c//consensus.fa TMPDIR=/home/gaoy1/sdata/umi_nc/951c/tmp/ MAX_RECORDS_IN_RAM=50000

```

**Comment by ucagenomix** [comment]
ok not a lot of information from the logs...
is there some output in your temporary directory ? Does it exists ? (TMPDIR=/home/gaoy1/sdata/umi_nc/951c/tmp/)
it takes a long time to process the whole bam file, when i do the consensus calling i process on a per chromosome basis and deduplicate the molecules using DeduplicateMolecule pipeline. Maybe you can give a try to the Y chromosome only and compare between 190 and 951 dataset to find out why it works with the 190 and not the 951 cells. 
Sorry not to able to be more precise, it is weird that it works with the 190 and not the 951 cells dataset.

I've changed this part to get the QV values in fastq file in the v2 using spoa not in the v1 using poa, do you have the UQ tag in the bam file ?

**Comment by yangao07** [comment]
The tmp dir is empty.
I will try to run it in a per-chromosome manner.
There is no UQ tag in `GEUS10xAttributes_umifound_.bam`.
Is that because I used `Sicelore-1.0.jar` instead of `Sicelore-2.0.jar`?
