### ISSUE TITLE
Sicelore-2.0.jar ComputeConsensus exception in LongreadParser

### ISSUE THREAD

**Issue by jbeaulaurier** [ucagenomix/sicelore#45]
Any help in decoding this exception would be greatly appreciated. Permissions to the temp directory should not be an issue and I have the following executables in my PATH:
- spoa
- picard
- samtools
- minimap2
- racon

If I revert back to Sicelore-1.0.jar, I'm able to produce a consensus FASTA file.

### Command ###
```
java -jar -Xmx22g ~/projects_new/software/sicelore/Jar/Sicelore-2.0.jar ComputeConsensus I=8-ont_merge/hsmm.GEUS10xAttributes_umifound_.bam O=hsmm.molecules.fastq T=4 TMPDIR=/home/temp/
```

### Output ###
[Wed Aug 04 00:02:38 BST 2021] ComputeConsensus INPUT=8-ont_merge/hsmm.GEUS10xAttributes_umifound_.bam OUTPUT=hsmm.molecules.fastq NTHREADS=4 TMPDIR=/home/temp/    CELLTAG=BC UMITAG=U8 GENETAG=IG TSOENDTAG=TE UMIENDTAG=UE POLYAENDTAG=PE USTAG=US RNTAG=RN MAXCLIP=150 MAPQV0=false MAXREADS=20 MINPS=3 MAXPS=20 DEBUG=false VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Wed Aug 04 00:02:38 BST 2021] Executing as jbeaulaurier@porpoisehead00 on Linux 4.4.0-142-generic amd64; OpenJDK 64-Bit Server VM 11.0.9.1-internal+0-adhoc..src; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: null
INFO    2021-08-04 00:02:38     LongreadParser          start...

> java.lang.NullPointerException
>         at org.ipmc.sicelore.utils.LongreadRecord.fromSAMRecord(LongreadRecord.java:91)
>         at org.ipmc.sicelore.utils.LongreadParser.parseSAMRecord(LongreadParser.java:100)
>         at org.ipmc.sicelore.utils.LongreadParser.<init>(LongreadParser.java:62)
>         at org.ipmc.sicelore.programs.ComputeConsensus.doWork(ComputeConsensus.java:100)
>         at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:277)
>         at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
>         at org.ipmc.sicelore.cmdline.SiCeLoReMain.main(SiCeLoReMain.java:40)

INFO    2021-08-04 00:02:38     LongreadParser          end...
INFO    2021-08-04 00:02:38     LongreadParser          Total SAMrecords        0
INFO    2021-08-04 00:02:38     LongreadParser          SAMrecords valid        0
INFO    2021-08-04 00:02:38     LongreadParser          SAMrecords unvalid      0
INFO    2021-08-04 00:02:38     LongreadParser          SAMrecords mapqv=0      0
INFO    2021-08-04 00:02:38     LongreadParser          SAMrecords no gene      0
INFO    2021-08-04 00:02:38     LongreadParser          SAMrecords no UMI       0
INFO    2021-08-04 00:02:38     LongreadParser          SAMrecords chimeria     0
INFO    2021-08-04 00:02:38     LongreadParser          SAMrecords reversed     0
INFO    2021-08-04 00:02:38     LongreadParser          Total reads             0
INFO    2021-08-04 00:02:38     LongreadParser          Total reads multiSAM    0
INFO    2021-08-04 00:02:38     MoleculeDataset         MoleculeDataset init start...
INFO    2021-08-04 00:02:38     MoleculeDataset         Total molecules         0
INFO    2021-08-04 00:02:38     MoleculeDataset         Total molecule reads    0
INFO    2021-08-04 00:02:38     MoleculeDataset         Total molecule multiIG  0
INFO    2021-08-04 00:02:38     MoleculeDataset         Calling consensus start with 4 threads
INFO    2021-08-04 00:02:38     MoleculeDataset         Total consensus to compute      0
[Wed Aug 04 00:02:38 BST 2021] org.ipmc.sicelore.programs.ComputeConsensus done. Elapsed time: 0.00 minutes.
Runtime.totalMemory()=2147483648

**Comment by jbeaulaurier** [comment]
Closing this because a new `git pull` solved the problem for me.
