### ISSUE TITLE
Sicelore-2.0.jar ComputeConsensus Produces a large number of IO errors

### ISSUE THREAD

**Issue by markme123** [ucagenomix/sicelore#48]
java -jar -Xmx250g /public/home/jiangmian/Soft/sicelore/Jar/Sicelore-2.0.jar ComputeConsensus I=GEUS10xAttributes_umifound_.bam O=consensus.fq T=64 TMPDIR=tmp

----------------------------------------------------------------------------------------------------
....................................................................
INFO    2021-09-03 00:23:18     LongreadParser          Total reads multiSAM    5
INFO    2021-09-03 00:23:18     MoleculeDataset         MoleculeDataset init start...
INFO    2021-09-03 00:28:03     MoleculeDataset         Total molecules         30380577
INFO    2021-09-03 00:28:17     MoleculeDataset         Total molecule reads    35460485
INFO    2021-09-03 00:28:17     MoleculeDataset         Total molecule multiIG  40413
INFO    2021-09-03 00:28:17     MoleculeDataset         Calling consensus start with 64 threads
INFO    2021-09-03 00:34:43     MoleculeDataset         Total consensus to compute      30380577
java.io.FileNotFoundException: tmp/CGCATGGGTGTCTTCC-AATTCTTTTTTC-3.msa (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at java.io.FileReader.<init>(FileReader.java:58)
        at org.ipmc.sicelore.utils.ConsensusMsa.<init>(ConsensusMsa.java:27)
        at org.ipmc.sicelore.utils.Consensus.call(Consensus.java:225)
        at org.ipmc.sicelore.utils.Consensus.call(Consensus.java:14)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
java.io.FileNotFoundException: tmp/GTACAGTCACACCAGC-CAATATTATTGA-3.msa (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at java.io.FileReader.<init>(FileReader.java:58)
        at org.ipmc.sicelore.utils.ConsensusMsa.<init>(ConsensusMsa.java:27)
        at org.ipmc.sicelore.utils.Consensus.call(Consensus.java:225)
.......................

**Comment by ucagenomix** [comment]
could you try to give the full path to the TMPDIR and be sure it exists and you have right permissions.
you have 30M molecules for 35M reads so probably very few molecules with RN >= 3 for which a consensus sequence is calculated.
