### ISSUE TITLE
Sicelore-2.0.jar IsoformMatrix runs into NoSuchElementException error

### ISSUE THREAD

**Issue by areebapatel** [ucagenomix/sicelore#51]
[Fri Sep 24 13:47:51 CEST 2021] IsoformMatrix INPUT=/b06x-isilon/b06x-m/mnp_nanopore/analysis/SC0003/sicelore_v2_hg38/240592.molecule.tags.GE.bam REFFLAT=/b06x-isilon/b06x-m/mnp_nanopore/software/hg38/refFlat.txt CSV=/omics/groups/OE0146/internal/Areeba/Visium/240592/outs/filtered_feature_bc_matrix/barcodes.tsv DELTA=2 OUTDIR=/b06x-isilon/b06x-m/mnp_nanopore/analysis/SC0003/sicelore_v2_hg38 PREFIX=sicmol ISOBAM=true METHOD=STRICT GENETAG=GE VALIDATION_STRINGENCY=SILENT    CELLTAG=BC UMITAG=U8 TSOENDTAG=TE UMIENDTAG=UE POLYAENDTAG=PE USTAG=US RNTAG=RN MAXCLIP=150 AMBIGUOUS_ASSIGN=false MAPQV0=false VERBOSITY=INFO QUIET=false COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Fri Sep 24 13:47:51 CEST 2021] Executing as a390l@odcf-cn33u24s08 on Linux 3.10.0-1160.41.1.el7.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_302-b08; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: null
INFO	2021-09-24 13:47:51	IsoformMatrix		Cells detected		[1297]
INFO	2021-09-24 13:47:51	LongreadParser		start...
INFO	2021-09-24 13:48:34	LongreadParser		Processed	     1,000,000 Records.  Elapsed time: 00:00:43s.  Time for last 1,000,000:   42s.  Last read position: chr2:231,048,385
INFO	2021-09-24 13:49:24	LongreadParser		end...
INFO	2021-09-24 13:49:24	LongreadParser		Total SAMrecords	1937911
INFO	2021-09-24 13:49:24	LongreadParser		SAMrecords valid	1199273
INFO	2021-09-24 13:49:24	LongreadParser		SAMrecords unvalid	738638
INFO	2021-09-24 13:49:24	LongreadParser		SAMrecords mapqv=0	25528
INFO	2021-09-24 13:49:24	LongreadParser		SAMrecords no gene	707994
INFO	2021-09-24 13:49:24	LongreadParser		SAMrecords no UMI	0
INFO	2021-09-24 13:49:24	LongreadParser		SAMrecords chimeria	5116
INFO	2021-09-24 13:49:24	LongreadParser		SAMrecords reversed	0
INFO	2021-09-24 13:49:24	LongreadParser		Total reads		1199191
INFO	2021-09-24 13:49:24	LongreadParser		Total reads multiSAM	82
INFO	2021-09-24 13:49:24	MoleculeDataset		MoleculeDataset init start...
INFO	2021-09-24 13:49:34	MoleculeDataset		Total molecules		1199191
INFO	2021-09-24 13:49:34	MoleculeDataset		Total molecule reads	1199191
INFO	2021-09-24 13:49:34	MoleculeDataset		Total molecule multiIG	32456
INFO	2021-09-24 13:49:34	UCSCRefFlatParser	UCSCRefFlatParser	start...
INFO	2021-09-24 13:49:36	UCSCRefFlatParser	UCSCRefFlatParser	end...
INFO	2021-09-24 13:49:36	UCSCRefFlatParser	Number of Genes Symbols	[28278]
INFO	2021-09-24 13:49:36	UCSCRefFlatParser	Number of Transcripts	[78363]
INFO	2021-09-24 13:49:36	MoleculeDataset		SetIsoforms		start...
java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at org.ipmc.sicelore.utils.MoleculeDataset.getMostComplexGene(MoleculeDataset.java:285)
	at org.ipmc.sicelore.utils.MoleculeDataset.setIsoformStrictNew(MoleculeDataset.java:258)
	at org.ipmc.sicelore.utils.MoleculeDataset.setIsoforms(MoleculeDataset.java:138)
	at org.ipmc.sicelore.programs.IsoformMatrix.process(IsoformMatrix.java:102)
	at org.ipmc.sicelore.programs.IsoformMatrix.doWork(IsoformMatrix.java:92)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:277)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
	at org.ipmc.sicelore.cmdline.SiCeLoReMain.main(SiCeLoReMain.java:40)
[Fri Sep 24 13:49:37 CEST 2021] org.ipmc.sicelore.programs.IsoformMatrix done. Elapsed time: 1.77 minutes.
Runtime.totalMemory()=4193255424
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:659)
	at java.util.ArrayList.get(ArrayList.java:435)
	at org.ipmc.sicelore.utils.MoleculeDataset.getMostComplexGene(MoleculeDataset.java:290)
	at org.ipmc.sicelore.utils.MoleculeDataset.setIsoformStrictNew(MoleculeDataset.java:258)
	at org.ipmc.sicelore.utils.MoleculeDataset.setIsoforms(MoleculeDataset.java:138)
	at org.ipmc.sicelore.programs.IsoformMatrix.process(IsoformMatrix.java:102)
	at org.ipmc.sicelore.programs.IsoformMatrix.doWork(IsoformMatrix.java:92)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:277)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
	at org.ipmc.sicelore.cmdline.SiCeLoReMain.main(SiCeLoReMain.java:40)

**Comment by ucagenomix** [comment]
might be a problem with refflat.txt you use, check that it is well formated, you can compare with the one provided in Gencode directory : gencode.v31.hg38.refFlat.txt

**Comment by areebapatel** [comment]
I am using the Gencode hg38 refFlat.txt file. I have also used the same file for another sample, and it worked well.

**Comment by ucagenomix** [comment]
Please visit Sicelore-2.1 github repository for this issue:
[https://github.com/ucagenomix/sicelore-2.1](https://github.com/ucagenomix/sicelore-2.1)
