### ISSUE TITLE
the problem of AddBamReadSequenceTag

### ISSUE THREAD

**Issue by lipidong** [ucagenomix/sicelore#53]
using the part data of all data from the paper(SRR9008425), I meet the error.

the input file:

SRR9008425.part_040.part_001.fastqFWD.gz  has 197989 reads

samtools falgstat test03.mm10.GN.0.bam  

```
360597 + 0 in total (QC-passed reads + QC-failed reads)
161210 + 0 secondary
1402 + 0 supplementary
0 + 0 duplicates
360597 + 0 mapped (100.00% : N/A)
```

while the output GEUS.bam dont include any reads.

belew is the command line and the log.

Thank you in advance

```
java -jar Jar/Sicelore-2.0.jar AddBamReadSequenceTag I=/home/xxx/work/wdl/test_projects/OntSingleCell/test01/test03/sicelore/split/GN/test03.mm10.GN.0.bam O=output_dir/GEUS.bam FASTQ=/home/xxx/work/wdl/test_projects/OntSingleCell/test01/test03/sicelore/split/passed/SRR9008425.part_040.part_001.fastqFWD.gz VALIDATION_STRINGENCY=SILENT
INFO    2021-11-08 21:41:48     AddBamReadSequenceTag

********** NOTE: Picard's command line syntax is changing.
**********
********** For more information, please see:
********** https://github.com/broadinstitute/picard/wiki/Command-Line-Syntax-Transition-For-Users-(Pre-Transition)
**********
********** The command line looks like this in the new syntax:
**********
**********    AddBamReadSequenceTag -I /home/xxx/work/wdl/test_projects/OntSingleCell/test01/test03/sicelore/split/GN/test03.mm10.GN.0.bam -O output_dir/GEUS.bam -FASTQ /home/xxx/work/wdl/test_projects/OntSingleCell/test01/test03/sicelore/split/passed/SRR9008425.part_040.part_001.fastqFWD.gz -VALIDATION_STRINGENCY SILENT
**********


[Mon Nov 08 21:41:48 CST 2021] AddBamReadSequenceTag INPUT=/home/xxx/work/wdl/test_projects/OntSingleCell/test01/test03/sicelore/split/GN/test03.mm10.GN.0.bam OUTPUT=output_dir/GEUS.bam FASTQ=/home/xxx/work/wdl/test_projects/OntSingleCell/test01/test03/sicelore/split/passed/SRR9008425.part_040.part_001.fastqFWD.gz VALIDATION_STRINGENCY=SILENT    SEQTAG=US QVTAG=UQ VERBOSITY=INFO QUIET=false COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Mon Nov 08 21:41:48 CST 2021] Executing as xx@slurm-login-node3 on Linux 3.10.0-1160.42.2.el7.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_152-release-1056-b12; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: null
INFO    2021-11-08 21:41:48     AddBamReadSequenceTag   loadFastq       START...
java.lang.ArrayIndexOutOfBoundsException: 0
        at org.ipmc.sicelore.utils.FastqLoader.<init>(FastqLoader.java:35)
        at org.ipmc.sicelore.programs.AddBamReadSequenceTag.doWork(AddBamReadSequenceTag.java:46)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:303)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
        at org.ipmc.sicelore.cmdline.SiCeLoReMain.main(SiCeLoReMain.java:40)
INFO    2021-11-08 21:41:48     AddBamReadSequenceTag   loadFastq       4421 reads loaded
INFO    2021-11-08 21:41:48     AddBamReadSequenceTag   addTag          START...
java.lang.NullPointerException
        at java.lang.String.<init>(String.java:566)
        at org.ipmc.sicelore.programs.AddBamReadSequenceTag.doWork(AddBamReadSequenceTag.java:61)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:303)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
        at org.ipmc.sicelore.cmdline.SiCeLoReMain.main(SiCeLoReMain.java:40)
[Mon Nov 08 21:41:48 CST 2021] org.ipmc.sicelore.programs.AddBamReadSequenceTag done. Elapsed time: 0.01 minutes.
Runtime.totalMemory()=253231104`

```

**Comment by lipidong** [comment]
I have solved the problem.
The input FASTQ must be fastq instead of fastq.gz.
