### ISSUE TITLE
NanoporeBC_UMI_finder-1.0.jar runs very long

### ISSUE THREAD

**Issue by erosix** [ucagenomix/sicelore#66]
Is normal that NanoporeBC_UMI_finder-1.0.jar takes very long to run. I am running it with 20 CPUs and 64 GB of RAM and is running for more than 24h. I am using the test data provided on GitHub. Is this supposed to be? Does it need different parameters?

Thank you in advance.

**Comment by ucagenomix** [comment]
Hi,
could you please check the quickrun.v2.sh is running fine on your system ? 
here is the output you should obtain :
**more output_dir/sicmol_isometrics.txt
geneId  transcriptId    nbExons nbUmis
Clta    undef   0       66
Clta    ENSMUST00000107851.9    7       8
Clta    ENSMUST00000170241.7    5       196
Clta    ENSMUST00000107845.3    5       11
Clta    ENSMUST00000107847.9    6       5
Clta    ENSMUST00000107849.9    6       313**

thanks,
kevin

**Comment by m-kuoch** [comment]
Hello, I'm also having an issue where the NanoporeBC_UMI_finder-1.0.jar runs and does not finish.

quickrun.v2.sh runs but gives me a different output:
```
geneId	transcriptId	nbExons	nbUmis
Clta	undef	0	19
Clta	ENSMUST00000170241.7	5	21
Clta	ENSMUST00000107845.3	5	1
Clta	ENSMUST00000107847.9	6	2
Clta	ENSMUST00000107849.9	6	29
```

When running quickrun.v2.sh, there are lots of` java.lang.NullPointerException` errors at `ConsensusMsa.java:51`
Is there a potential fox for this?

Thanks in advance.

**Comment by erosix** [comment]
Same here. My log files looks like:

`O.K. Found and using /opt/sicelore/Jar/bcMaxEditDistances.xml
***** Will generate 8threads
2022-04-22 16:22:53 DEBUG NanoPoreSeqAnalyzer_new:201 - Read : 58141c88-02ea-4c4b-896b-2dde090b425c_FWD_pA_Ad3p_TSO5p failed
java.lang.NullPointerException: null
	at com.rw.nuc.encoding.onebyte.NucleicAcidInmutableOneBytePerBase.<init>(NucleicAcidInmutableOneBytePerBase.java:283) ~[TwoFourBitNucAcidLibraryMaven-1.0.jar:?]
	at com.rw.nuc.encoding.onebyte.NucleicAcidOneBytePerBase.<init>(NucleicAcidOneBytePerBase.java:43) ~[TwoFourBitNucAcidLibraryMaven-1.0.jar:?]
	at com.rw.illuminaoxfordmerger.analyzers.PolyATadapterInternalSearcher.<init>(PolyATadapterInternalSearcher.java:45) ~[NanoporeBC_UMI_finder-1.0.jar:?]
	at com.rw.illuminaoxfordmerger.OneNanoporeSeqAnalyzer.analyze(OneNanoporeSeqAnalyzer.java:71) ~[NanoporeBC_UMI_finder-1.0.jar:?]
	at com.rw.illuminaoxfordmerger.NanoPoreSeqAnalyzer_new$NanoporeSeqListWorker.call(NanoPoreSeqAnalyzer_new.java:195) [NanoporeBC_UMI_finder-1.0.jar:?]
	at com.rw.illuminaoxfordmerger.NanoPoreSeqAnalyzer_new$NanoporeSeqListWorker.call(NanoPoreSeqAnalyzer_new.java:172) [NanoporeBC_UMI_finder-1.0.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_312]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_312]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_312]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]

......
`

followed by:

`
2022-04-22 16:22:57 DEBUG NanoPoreSeqAnalyzer_new:201 - Read : c9fb718f-2adc-4ee3-8c4a-f1ac5b10e8f3_REV_pT_Ad5p_TSO3p failed
java.lang.NullPointerException: null
2022-04-22 16:22:57 DEBUG NanoPoreSeqAnalyzer_new:201 - Read : 7dc80c82-e78f-482f-bcb0-7d76540305ed_FWD_pA_Ad3p_TSO5p failed
java.lang.NullPointerException: null
2022-04-22 16:22:57 DEBUG NanoPoreSeqAnalyzer_new:201 - Read : 491af656-a9dc-40e0-89ee-0c9c2b78e334_REV_pT_Ad5p_TSO3p failed
java.lang.NullPointerException: null
2022-04-22 16:22:57 DEBUG NanoPoreSeqAnalyzer_new:201 - Read : ac8a4870-6a93-4a57-93f0-cd3b3b4284fe_FWD_pA_Ad3p_TSO5p failed
`

and then it gets stuck there. I think it finds some issue but does not have an option to stop so it just stays there forever. It would be good to understand which is the issue and how to in case throw an error message and stop the process when this happens.

**Comment by erosix** [comment]
Problem here was at the level of AddBamReadSequenceTag function. The programs keeps running even if one of the outputs is empty i.e. GE or GEUS.bam files, which causes issues with NanoporeBC_UMI_finder-1.0.jar issues. Perhaps it would be good to add a checkpoint at the start of each script to check that the input file is not empty.
