### ISSUE TITLE
Error when running IlluminaParser.jar

### ISSUE THREAD

**Issue by RCHENLAB** [ucagenomix/sicelore#72]
Hello,
I'm encountering the following error while executing this command:

$java -Xmx250G -XX:-UseGCOverheadLimit -XX:+UseConcMarkSweepGC -jar ${shell_dir}/IlluminaParser-1.0.jar -i ${scbam}.bam -o $obj -t ${cellbc} -b CB -g GN -u UB

``
Exception in thread "main" htsjdk.samtools.FileTruncatedException: Premature end of file: data stream
        at htsjdk.samtools.util.BlockCompressedInputStream.processNextBlock(BlockCompressedInputStream.java:530)
        at htsjdk.samtools.util.BlockCompressedInputStream.nextBlock(BlockCompressedInputStream.java:468)
        at htsjdk.samtools.util.BlockCompressedInputStream.readBlock(BlockCompressedInputStream.java:458)
        at htsjdk.samtools.util.BlockCompressedInputStream.available(BlockCompressedInputStream.java:196)
        at htsjdk.samtools.util.BlockCompressedInputStream.read(BlockCompressedInputStream.java:331)
        at java.io.DataInputStream.read(DataInputStream.java:149)
        at htsjdk.samtools.util.BinaryCodec.readBytesOrFewer(BinaryCodec.java:421)
        at htsjdk.samtools.util.BinaryCodec.readBytes(BinaryCodec.java:394)
        at htsjdk.samtools.util.BinaryCodec.readByteBuffer(BinaryCodec.java:507)
        at htsjdk.samtools.util.BinaryCodec.readInt(BinaryCodec.java:518)
        at htsjdk.samtools.BAMRecordCodec.decode(BAMRecordCodec.java:261)
        at htsjdk.samtools.BAMFileReader$BAMFileIterator.getNextRecord(BAMFileReader.java:866)
        at htsjdk.samtools.BAMFileReader$BAMFileIterator.advance(BAMFileReader.java:840)
        at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:834)
        at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:802)
        at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:574)
        at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:553)
        at com.rw.bamparsermaven.Parser.parse(Parser.java:125)
        at com.rw.bamparsermaven.Main.main(Main.java:99)
``

Any ideas what could be causing this?
Thanks,
Meng

**Comment by ucagenomix** [comment]
Please visit Sicelore-2.1 github repository for this issue:
[https://github.com/ucagenomix/sicelore-2.1](https://github.com/ucagenomix/sicelore-2.1)
