### ISSUE TITLE
error in illluminaparser

### ISSUE THREAD

**Issue by yuanwsy** [ucagenomix/sicelore#78]
when i am using the illuminaparser.jar,and the input bam is the 190c_possorted_genome_bam.bam(your data,downloaded from ENA),i met a bug like this
java -Xmx15000m -jar "/data/R02/yuanwsy/sicelore/Jar/IlluminaParser-1.0.jar" --inFileIllumina "/data/R02/yuanwsy/wgetdownload/190c_possorted_genome_bam.bam" --tsv "/data/R02/yuanwsy/sicelore/Barcodes/cellBC.190.tsv" --outFile /data/R02/yuanwsy/sicelore/test/190cparsedForNanopore_v0.2.obj --cellBCflag CB --umiFlag UB --geneFlag GN
+++++++   ILLUMINAPARSER 1.002_2Build Feb. 20, 2020++++++++++++
..................................................
..................................................
..................................................
..........................Exception in thread "main" htsjdk.samtools.SAMFormatException: Did not inflate expected amount
        at htsjdk.samtools.util.BlockGunzipper.unzipBlock(BlockGunzipper.java:147)
        at htsjdk.samtools.util.BlockGunzipper.unzipBlock(BlockGunzipper.java:96)
        at htsjdk.samtools.util.BlockCompressedInputStream.inflateBlock(BlockCompressedInputStream.java:550)
        at htsjdk.samtools.util.BlockCompressedInputStream.processNextBlock(BlockCompressedInputStream.java:532)
        at htsjdk.samtools.util.BlockCompressedInputStream.nextBlock(BlockCompressedInputStream.java:468)
        at htsjdk.samtools.util.BlockCompressedInputStream.readBlock(BlockCompressedInputStream.java:458)
        at htsjdk.samtools.util.BlockCompressedInputStream.available(BlockCompressedInputStream.java:196)
        at htsjdk.samtools.util.BlockCompressedInputStream.read(BlockCompressedInputStream.java:331)
        at java.io.DataInputStream.read(DataInputStream.java:149)
        at htsjdk.samtools.util.BinaryCodec.readBytesOrFewer(BinaryCodec.java:421)
        at htsjdk.samtools.util.BinaryCodec.readBytes(BinaryCodec.java:394)
        at htsjdk.samtools.util.BinaryCodec.readByteBuffer(BinaryCodec.java:507)
        at htsjdk.samtools.util.BinaryCodec.readInt(BinaryCodec.java:518)
        at htsjdk.samtools.BAMRecordCodec.decode(BAMRecordCodec.java:261)
        at htsjdk.samtools.BAMFileReader$BAMFileIterator.getNextRecord(BAMFileReader.java:866)
        at htsjdk.samtools.BAMFileReader$BAMFileIterator.advance(BAMFileReader.java:840)
        at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:834)
        at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:802)
        at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:574)
        at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:553)
        at com.rw.bamparsermaven.Parser.parse(Parser.java:125)
        at com.rw.bamparsermaven.Main.main(Main.java:99)
it seems that the input bam too big,i want to know when you using the bam as a input ,the way you solve the problem

**Comment by weiwei4396** [comment]
I have same problem. Have you solved it yet?
